baseURL = "http://example.org/"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Fixtures, Lighting, and Appliances"
parent = "Design & Remodeling Services"
url = "/plumbing-fixtures-appliances-lighting/"
weight = 1
[[menu.main]]
name = "Design & Remodeling Services"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 2
