baseURL = "http://example.org/"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Flooring"
parent = "Design & Remodeling Services"
url = "/flooring"
weight = 4
[[menu.main]]
name = "Cabinets, Countertops, Hardware"
parent = "Design & Remodeling Services"
url = "/cabinets-countertops-hardware/"
weight = 3
[[menu.main]]
name = "Tile, Backsplash, and Flooring"
parent = "Design & Remodeling Services"
url = "/tile-backsplash-showers-flooring/"
weight = 2
[[menu.main]]
name = "Fixtures, Lighting, and Appliances"
parent = "Design & Remodeling Services"
url = "/plumbing-fixtures-appliances-lighting/"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact-information"
weight = 3
[[menu.main]]
name = "Design & Remodeling Services"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
