---
label: Page Config
hide_body: true
fields:
- name: bathroom_remodels
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Bathroom Remodels
- name: cabinets
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Cabinets Counter Tops and Hardware
- name: contact_page
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Contact Page
- name: fixtures
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Fixtures Lighting and Appliances
- name: flooring
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Flooring
- name: kitchen_remodel
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Kitchen Remodel
- name: tile_work
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Tile Work
pages:
- data/pageconfig.yaml
